# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee567633a657d009f02370b8bc5c74c8b84074666858d94d0654adee05216a6b738d0973648a6654da023c6ee62027b2dc95b061c5c90e9c2ffccc3546335437

test:
  secret_key_base: 5100a4d3c9e5a5d5a5e493e62bb21fa7b5ef885a9e7a11b3e7b757b03ad88e5fa6a4d3f5b419065217b906681a3b1369aa736103f6c589007dad6174e7a3ad6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
